server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: fraud-service

  mongodb:
    host: ${SPRING_DATA_MONGODB_HOST:localhost}
    port: ${SPRING_DATA_MONGODB_PORT:27017}
    database: ${SPRING_DATA_MONGODB_DATABASE:paycore_fraud_db}
    username: ${SPRING_DATA_MONGODB_USERNAME:paycore}
    password: ${SPRING_DATA_MONGODB_PASSWORD:paycore}
    authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}

paycore:
  fraud:
    high-amount-threshold: 50000
    card-attempt-threshold: 3
    ip-attempt-threshold: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info