server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: merchant-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paycore_merchant_db}
    username: ${SPRING_DATASOURCE_USERNAME:paycore}
    password: ${SPRING_DATASOURCE_PASSWORD:paycore}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info