server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: payment-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paycore_payment_db}
    username: ${SPRING_DATASOURCE_USERNAME:paycore}
    password: ${SPRING_DATASOURCE_PASSWORD:paycore}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:paycore}
    password: ${SPRING_RABBITMQ_PASSWORD:paycore}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  merchant-service:
    base-url: ${MERCHANT_SERVICE_BASE_URL:http://localhost:8081}

  legacy-bank-soap-service:
    base-url: ${LEGACY_BANK_SOAP_SERVICE_BASE_URL:http://localhost:8084/ws}

  fraud-service:
    base-url: ${FRAUD_SERVICE_BASE_URL:http://localhost:8086}

paycore:
  kafka:
    topics:
      payment-events: payment-events

  rabbitmq:
    exchange: notification.exchange
    payment-notification-queue: payment.notification.queue
    payment-notification-routing-key: payment.notification.created

management:
  endpoints:
    web:
      exposure:
        include: health,info