spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: merchant-service
              uri: ${MERCHANT_SERVICE_URI:http://localhost:8081}
              predicates:
                - Path=/api/merchants/**

            - id: payment-service
              uri: ${PAYMENT_SERVICE_URI:http://localhost:8082}
              predicates:
                - Path=/api/payments/**